version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    networks:
      - spark-network
    ports:
      - "8080:8080"
      - "7077:7077"
    command: spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    networks:
      - spark-network
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - spark-master
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

networks:
  spark-network:
    driver: bridge