blob.server.port: 6124
rest.port: 8074
taskmanager.log.path: /opt/flink/log
taskmanager.memory.process.size: 1024m
jobmanager.web.log.path: /opt/flink/log
env.java.opts: -XX:+UnlockCommercialFeatures-XX:+FlightRecorder-XX:StartFlightRecording=filename=/opt/flink/jfr/taskmanager.jfr
jobmanager.rpc.address: jobmanager
taskmanager.numberOfTaskSlots: 20
jobmanager.web.submit.enable: true
jobmanager.memory.process.size: 1024m
query.server.port: 6125
#rest.flamegraph.enabled: true
