services:
  jobmanager:
    image: flink:latest
    container_name: flink-jobmanager
    ports:
      - "8084:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        env.java.opts: -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=filename=/opt/flink/jfr/jobmanager.jfr
    command: jobmanager
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_jobmanager_data:/opt/flink
      - ../service-data/flink/configs/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml # Mount custom flink-conf.yaml
    networks:
      - big-data-network

  taskmanager:
    image: flink:latest
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        env.java.opts: -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=filename=/opt/flink/jfr/taskmanager.jfr
    command: taskmanager
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://jobmanager:8081/taskmanagers | grep 'taskmanagers' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_taskmanager_data:/opt/flink
      - ../service-data/flink/configs/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml # Mount custom flink-conf.yaml
    networks:
      - big-data-network

volumes:
  flink_jobmanager_data:
    driver: local
  flink_taskmanager_data:
    driver: local

networks:
  big-data-network:
    external: true