services:
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    ports:
      - "9001:9000"
    environment:
      ZOOKEEPER_SERVERS: zookeeper:2181
      DISABLE_AUTH: "true"
    networks:
      - big-data-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  big-data-network:
    external: true