services:
  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    ports:
      - "9093:9093"
    volumes:
      - ../service-data/akhq/configs/application.yml:/app/application.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9093/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - big-data-network

networks:
  big-data-network:
    external: true