services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "8080:8080"  # Admin UI port
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: "srvr,ruok"
    volumes:
      - ../configs/zookeeper/zoo.cfg:/opt/bitnami/zookeeper/conf/zoo.cfg
      - ../app-data/zookeeper/volumes/data:/data
    healthcheck:
      test: ["CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s  # Add a start period to give the service time to initialize
    networks:
      - big-data-network

networks:
  big-data-network:
    external: true