services:
  jobmanager:
    image: flink-local
    container_name: flink-jobmanager
    ports:
      - "8074:8074"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        env.java.opts: -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=filename=/opt/flink/jfr/jobmanager.jfr
      - HADOOP_HOME=/opt/hadoop-3.3.6
      - HADOOP_CONF_DIR=/opt/hadoop-3.3.6/etc/hadoop
    command: /opt/flink/bin/jobmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8074 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_jobmanager_data:/opt/flink
      - ../configs/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml # mount for custom flink-conf.yaml
      - ../configs/hadoop:/opt/hadoop-3.3.6/etc/hadoop
      - ../app-data/flink/data:/opt/flink/data # mount for data files
      - ../app-data/flink/jars:/opt/flink/jars # mount for jar files
    networks:
      - big-data-network

  taskmanager:
    image: flink-local
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 20
        env.java.opts: -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -XX:StartFlightRecording=filename=/opt/flink/jfr/taskmanager.jfr
      - HADOOP_HOME=/opt/hadoop-3.3.6
      - HADOOP_CONF_DIR=/opt/hadoop-3.3.6/etc/hadoop
    command: /opt/flink/bin/taskmanager.sh start-foreground
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://jobmanager:8074/taskmanagers | grep 'taskmanagers' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - flink_taskmanager_data:/opt/flink
      - ../configs/flink/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml # mount for custom flink-conf.yaml
      - ../configs/hadoop:/opt/hadoop-3.3.6/etc/hadoop
      - ../app-data/flink/data:/opt/flink/data # mount for data files
      - ../app-data/flink/jars:/opt/flink/jars # mount for jar files
    networks:
      - big-data-network

volumes:
  flink_jobmanager_data:
    driver: local
  flink_taskmanager_data:
    driver: local

networks:
  big-data-network:
    external: true