services:
  yarn-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-resourcemanager
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - YARN_RESOURCEMANAGER_HOSTNAME=yarn-resourcemanager
    ports:
      - "8088:8088"  # YARN Resource Manager Web UI
    networks:
      - big-data-network

  yarn-nodemanager-1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-nodemanager-1
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - YARN_RESOURCEMANAGER_HOSTNAME=yarn-resourcemanager
    ports:
      - "8042:8042"  # YARN Node Manager Web UI
    networks:
      - big-data-network
    depends_on:
      - yarn-resourcemanager

  yarn-nodemanager-2:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: yarn-nodemanager-2
    platform: linux/amd64
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - YARN_RESOURCEMANAGER_HOSTNAME=yarn-resourcemanager
    ports:
      - "8043:8042"  # YARN Node Manager Web UI
    networks:
      - big-data-network
    depends_on:
      - yarn-resourcemanager

networks:
  big-data-network:
    external: true