version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - pinot-demo

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - pinot-demo

  pinot-controller:
    image: apachepinot/pinot:latest
    command: "StartController -zkAddress zookeeper:2181"
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
    networks:
      - pinot-demo
    volumes:
      - ./config:/config

  pinot-broker:
    image: apachepinot/pinot:latest
    command: "StartBroker -zkAddress zookeeper:2181"
    ports:
      - "8099:8099"
    depends_on:
      - zookeeper
      - pinot-controller
    networks:
      - pinot-demo

  pinot-server:
    image: apachepinot/pinot:latest
    command: "StartServer -zkAddress zookeeper:2181"
    ports:
      - "8098:8098"
    depends_on:
      - zookeeper
      - pinot-controller
    networks:
      - pinot-demo

  pinot-minion:
    image: apachepinot/pinot:latest
    command: "StartMinion -zkAddress zookeeper:2181"
    ports:
      - "9514:9514"
    depends_on:
      - zookeeper
      - pinot-controller
    networks:
      - pinot-demo

networks:
  pinot-demo:
    driver: bridge