version: '3.8'

services:
  pinot-controller:
    image: apachepinot/pinot:latest
    container_name: pinot-controller
    ports:
      - "9000:9000"
    environment:
      - PINOT_CLUSTER_NAME=pinot-cluster
      - PINOT_ZOOKEEPER_URL=zookeeper:2181
      - PINOT_CONTROLLER_HOST=pinot-controller
      - PINOT_CONTROLLER_PORT=9000
    networks:
      - kafka-network
    command: "StartController"

  pinot-broker:
    image: apachepinot/pinot:latest
    container_name: pinot-broker
    ports:
      - "8099:8099"
    environment:
      - PINOT_CLUSTER_NAME=pinot-cluster
      - PINOT_ZOOKEEPER_URL=zookeeper:2181
      - PINOT_BROKER_HOST=pinot-broker
      - PINOT_BROKER_PORT=8099
    networks:
      - kafka-network
    command: "StartBroker"

  pinot-server:
    image: apachepinot/pinot:latest
    container_name: pinot-server
    ports:
      - "8097:8097"
    environment:
      - PINOT_CLUSTER_NAME=pinot-cluster
      - PINOT_ZOOKEEPER_URL=zookeeper:2181
      - PINOT_SERVER_HOST=pinot-server
      - PINOT_SERVER_PORT=8097
    networks:
      - kafka-network
    command: "StartServer"

  pinot-minion:
    image: apachepinot/pinot:latest
    container_name: pinot-minion
    ports:
      - "8098:8098"
    environment:
      - PINOT_CLUSTER_NAME=pinot-cluster
      - PINOT_ZOOKEEPER_URL=zookeeper:2181
      - PINOT_MINION_HOST=pinot-minion
      - PINOT_MINION_PORT=8098
    networks:
      - kafka-network
    command: "StartMinion"

networks:
  kafka-network:
    external: true