services:
  hadoop-namenode:
    image: apache/hadoop:3.3.6-arm64
    container_name: hadoop-namenode
    hostname: hadoop-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_namenode_name_dir=file:///hadoop_data/hdfs/namenode
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS RPC
    volumes:
      - ./data/hadoop/namenode:/hadoop_data/hdfs/namenode
    command: ["hdfs", "namenode"]
    networks:
      - hadoop

  hadoop-datanode:
    image: apache/hadoop:3.3.6-arm64
    container_name: hadoop-datanode
    hostname: hadoop-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop_data/hdfs/datanode
    volumes:
      - ./data/hadoop/datanode:/hadoop_data/hdfs/datanode
    depends_on:
      - hadoop-namenode
    command: ["hdfs", "datanode"]
    networks:
      - hadoop

  yarn-resourcemanager:
    image: apache/hadoop:3.3.6-arm64
    container_name: yarn-resourcemanager
    hostname: yarn-resourcemanager
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=yarn-resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    ports:
      - "8088:8088"  # ResourceManager Web UI
    depends_on:
      - hadoop-namenode
    command: ["yarn", "resourcemanager"]
    networks:
      - hadoop

  yarn-nodemanager:
    image: apache/hadoop:3.3.6-arm64
    container_name: yarn-nodemanager
    hostname: yarn-nodemanager
    environment:
      - YARN_CONF_yarn_resourcemanager_hostname=yarn-resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
    depends_on:
      - yarn-resourcemanager
    command: ["yarn", "nodemanager"]
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge

volumes:
  namenode-data:
  datanode-data:
